"use client";

/**
 * MiniChallengeWidget - inline MCQ for student practice.
 * Generated by the mentor agent on-the-fly - not persisted to DB.
 */
import { useState } from "react";
import { cn } from "@/lib/utils";
import { Check, X } from "lucide-react";

interface MCQOption {
  text: string;
  is_correct: boolean;
  explanation?: string;
}

interface MiniChallengeWidgetProps {
  props: {
    question: string;
    options: MCQOption[];
    concept?: string;
  };
}

export function MiniChallengeWidget({ props }: MiniChallengeWidgetProps) {
  const { question, options, concept } = props;
  const [selected, setSelected] = useState<number | null>(null);
  const [revealed, setRevealed] = useState(false);

  if (!options || options.length === 0) return null;

  function handleSelect(index: number) {
    if (revealed) return;
    setSelected(index);
    setRevealed(true);
  }

  const isCorrect = selected !== null && options[selected]?.is_correct;

  return (
    <div className="space-y-3 mt-2">
      <div className="text-xs font-bold text-blue-600 dark:text-cyan-400 uppercase tracking-wider">
        Mini Challenge {concept && `- ${concept}`}
      </div>

      <div className="p-4 rounded-xl bg-white dark:bg-[#0F1E35] border border-slate-200/80 dark:border-blue-500/20 shadow-xs dark:shadow-none">
        <p className="text-sm font-semibold text-slate-800 dark:text-slate-100 mb-3">
          {question}
        </p>

        <div className="space-y-2">
          {options.map((opt, i) => {
            const isSelected = selected === i;
            const showCorrect = revealed && opt.is_correct;
            const showWrong = revealed && isSelected && !opt.is_correct;

            return (
              <button
                key={i}
                onClick={() => handleSelect(i)}
                disabled={revealed}
                className={cn(
                  "w-full text-left flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-medium",
                  "border transition-all duration-200",
                  !revealed
                    ? "border-slate-200 dark:border-blue-500/20 hover:border-blue-400 dark:hover:border-cyan-400 hover:bg-blue-50/50 dark:hover:bg-[#162644] active:scale-[0.98]"
                    : showCorrect
                      ? "border-emerald-300 dark:border-emerald-800 bg-emerald-50 dark:bg-emerald-950/20 text-emerald-900 dark:text-emerald-300"
                      : showWrong
                        ? "border-rose-300 dark:border-rose-800 bg-rose-50 dark:bg-rose-950/20 text-rose-900 dark:text-rose-300"
                        : "border-slate-200 dark:border-blue-500/10 opacity-50",
                  "disabled:cursor-default",
                )}
              >
                <span
                  className={cn(
                    "w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0",
                    showCorrect
                      ? "bg-emerald-500 text-white"
                      : showWrong
                        ? "bg-rose-500 text-white"
                        : "bg-slate-100 dark:bg-[#070E1C] text-slate-500 dark:text-slate-400",
                  )}
                >
                  {showCorrect ? (
                    <Check className="w-3.5 h-3.5" />
                  ) : showWrong ? (
                    <X className="w-3.5 h-3.5" />
                  ) : (
                    String.fromCharCode(65 + i)
                  )}
                </span>
                <span
                  className={cn(
                    showCorrect
                      ? "text-emerald-800 dark:text-emerald-300 font-semibold"
                      : showWrong
                        ? "text-rose-800 dark:text-rose-300 font-semibold"
                        : "text-slate-700 dark:text-slate-200",
                  )}
                >
                  {opt.text}
                </span>
              </button>
            );
          })}
        </div>

        {/* Result feedback */}
        {revealed && (
          <div
            className={cn(
              "mt-3 p-3 rounded-xl text-xs font-semibold leading-relaxed",
              isCorrect
                ? "bg-emerald-50 dark:bg-emerald-950/30 text-emerald-700 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-900/50"
                : "bg-rose-50 dark:bg-rose-950/30 text-rose-700 dark:text-rose-300 border border-rose-200 dark:border-rose-900/50",
            )}
          >
            {isCorrect ? "Chính xác! 🎉" : "Chưa chính xác."}
            {selected !== null && options[selected]?.explanation && (
              <p className="mt-1 text-slate-600 dark:text-slate-350 text-xs font-normal">
                {options[selected].explanation}
              </p>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
